### ISSUE TITLE
topo_rein.query_to_topojson fails when no rows in table

### ISSUE THREAD

**Issue by larsop** [NibioOpenSource/pgtopo_update_sql#8]
[local] lop@sl=# select reinbeitebruker_id, reindrift_sesongomrade_kode, omrade from topo_rein.arstidsbeite_var_flate;
 reinbeitebruker_id | reindrift_sesongomrade_kode | omrade 
--------------------+-----------------------------+--------
(0 rows)

[local] lop@sl=# SELECT  topo_rein.query_to_topojson('select \* from topo_rein.arstidsbeite_var_flate', 32632, 0);
ERROR:  P0001: No TopoGeometry field in query result
LOCATION:  exec_stmt_raise, pl_exec.c:3068
[local] lop@sl=#

**Comment by strk** [comment]
The function relies on getting a result in order to find the
TopoGeometry object. Thus the error. Having no TopoGeometry makes
it also impossible to know what the Topology is, so the CRS.

Should it then output something like this ?

```
{"type":"Topology", "objects":{},"arcs":[]}
```

Or this:

```
{"type":"Topology", "objects":{}}
```

Or this:

```
{"type":"Topology"}
```

Or even this:

```
{}
```

Or.. a NULL ?

Pick one :)

**Comment by strk** [comment]
I went with a NULL return, feel free to reopen if you don't like it.

**Comment by larsop** [comment]
Thanks thats just fine.
